### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mandibles23** [ksdmitrieva/electrolint#1]
Greetings, we are piloting your tool. NPM install runs just fine but compile fails. Could it be my version of Node? Thank you! 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/[userid]/.nvm/versions/node/v14.15.0/bin/node',
1 verbose cli   '/Users/[userid]/.nvm/versions/node/v14.15.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle electrolint@1.0.0~precompile: electrolint@1.0.0
6 info lifecycle electrolint@1.0.0~compile: electrolint@1.0.0
7 verbose lifecycle electrolint@1.0.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle electrolint@1.0.0~compile: PATH: /Users/[userid]/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/[userid]/electrolint/node_modules/.bin:/Users/[userid]/.nvm/versions/node/v14.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle electrolint@1.0.0~compile: CWD: /Users/[userid]/electrolint
10 silly lifecycle electrolint@1.0.0~compile: Args: [ '-c', 'tsc -b' ]
11 silly lifecycle electrolint@1.0.0~compile: Returned: code: 1  signal: null
12 info lifecycle electrolint@1.0.0~compile: Failed to exec compile script
13 verbose stack Error: electrolint@1.0.0 compile: `tsc -b`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/[userid]/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/[userid]/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid electrolint@1.0.0
15 verbose cwd /Users/[userid]/electrolint
16 verbose Darwin 19.6.0
17 verbose argv "/Users/[userid]/.nvm/versions/node/v14.15.0/bin/node" "/Users/[userid]/.nvm/versions/node/v14.15.0/bin/npm" "run" "compile"
18 verbose node v14.15.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error electrolint@1.0.0 compile: `tsc -b`
22 error Exit status 1
23 error Failed at the electrolint@1.0.0 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ksdmitrieva** [comment]
Thanks for your interest. This is the Node and npm versions I'm using:
```
$ node -v
v12.19.0
$ npm -v
6.14.8
```
Looks like you are using a newer version of Node (14.15.0 vs 12.19.0).
Let me know if that fixes your problem.

**Comment by mandibles23** [comment]
Thank you, I'll try this and write back. Much appreciated!

**Comment by mandibles23** [comment]
no luck, i see the same errors for 12.19.0. log looks the same. here's a sample of the console errors (i'm on a mac, xcode is always a wildcard)

 electrolint@1.0.0 compile /Users/[userid]/electrolint
> tsc -b

server/node_modules/vscode-languageserver/lib/callHierarchy.proposed.d.ts:5:58 - error TS2694: Namespace '"/Users/[userid]/electrolint/server/node_modules/vscode-languageserver-protocol/lib/common/api".Proposed' has no exported member 'CallHierarchyPrepareParams'.

5         onPrepare(handler: ServerRequestHandler<Proposed.CallHierarchyPrepareParams, Proposed.CallHierarchyItem[] | null, never, void>): void;
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

server/node_modules/vscode-languageserver/lib/callHierarchy.proposed.d.ts:5:95 - error TS2694: Namespace '"/Users/[userid]/electrolint/server/node_modules/vscode-languageserver-protocol/lib/common/api".Proposed' has no exported member 'CallHierarchyItem'.

5         onPrepare(handler: ServerRequestHandler<Proposed.CallHierarchyPrepareParams, Proposed.CallHierarchyItem[] | null, never, void>): void;
                                                                                                ~~~~~~~~~~~~~~~~~

server/node_modules/vscode-languageserver/lib/callHierarchy.proposed.d.ts:6:64 - error TS2694: Namespace '"/Users/[userid]/electrolint/server/node_modules/vscode-languageserver-protocol/lib/common/api".Proposed' has no exported member 'CallHierarchyIncomingCallsParams'.

6         onIncomingCalls(handler: ServerRequestHandler<Proposed.CallHierarchyIncomingCallsParams, Proposed.CallHierarchyIncomingCall[] | null, Proposed.CallHierarchyIncomingCall[], void>): void;
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server/node_modules/vscode-languageserver/lib/callHierarchy.proposed.d.ts:6:107 - error TS2694: Namespace '"/Users/[userid]/electrolint/server/node_modules/vscode-languageserver-protocol/lib/common/api".Proposed' has no exported member 'CallHierarchyIncomingCall'.

6         onIncomingCalls(handler: ServerRequestHandler<Proposed.CallHierarchyIncomingCallsParams, Proposed.CallHierarchyIncomingCall[] | null, Proposed.CallHierarchyIncomingCall[], void>): void;

**Comment by ksdmitrieva** [comment]
I haven't tested it on a Mac (I will try it out next), but looks like the error comes from the VSCode's language server library. I searched for the error from your console output, and it might be related to this issue reported for VSCode language server:
https://github.com/microsoft/vscode/issues/70231
